Added new components for the layout of login
NoSaBo/vpProject pull request #1
Opened 2018-08-09 02:50 UTC by NoSaBo

Added the components BoxButton, Input and Login

2018-08-09 03:02 UTC, walter-erquinigo requested changes
Usa prettier para autoformatear tu codigo, asi tienes un estilo consistente en todos tus archivos.
En general, con eso, escribes tu codigo sin preocuparte por el formate y luego prettier te lo arregla. 
Atom tiene un plugin para prettier https://atom.io/packages/prettier-atom.
Si no me equivoco, hay un setting para invocarlo cada que grabas un archivo, asi siempre esta todo formateado.
Tb hay un para vscode, si es que usas eso

2018-08-09 03:02 UTC, walter-erquinigo commented on App.test.js
> +  expect(rendered).toBeTruthy();
cute

2018-08-09 03:02 UTC, walter-erquinigo commented on README.old.md
> +# vpProject
me parece que tienes que borrar este archivo

2018-08-09 03:02 UTC, a20012251 commented on components/boxbutton.js
> +        // disable={this.props.disable}
borra esas lineas de comentario

2018-08-09 03:02 UTC, a20012251 commented on components/login.js
> +          // disable='true'
borra esto tb

2018-08-09 03:02 UTC, a20012251 commented on components/login.js
> +          // disable='true'
en general no incluyas codigo como comentario que luego pueda que vayas a usar, porque puede pasar que al final decides hacerlo de una manera diferente y los comentarios se quedan ahi confundiendo

2018-08-09 06:15 UTC, diegocl02 reviewed
Quiza puedas encontrar un nombre mejor al button y manten consitencia en los nombres de los archivos:
o bien todos 'PascalCase' o todos 'dash-case' (te recomiendo el ultimo). Por lo demas bien.

2018-08-09 21:35 UTC, NoSaBo commented on App.test.js
> +  expect(rendered).toBeTruthy();
eso viene en el default :sa:

2018-08-10 02:19 UTC, NoSaBo commented
Realice los cambios :)

2018-08-10 02:43 UTC, diegocl02 requested changes
Si estas usando dash-case para los archivos, entonces puedes cambiar:
App.js --> app.js
custombutton.js --> custom-button.js

2018-08-10 02:59 UTC, a20012251 commented
Dime que me quieres más que a Mariana

2018-08-11 18:23 UTC, closed without merging