screens controlSite and controlPhoto finished
NoSaBo/vpProject pull request #6
Opened 2018-09-07 03:09 UTC by renzo-c

Components added:

- controlSite-screen
- controlPhoto-screen
- App.js (navigator added)

2018-09-10 06:20 UTC, walter-erquinigo requested changes
usa el autoformatter y borra esas lineas que estan ahi por gusto. fuera de eso, esta bueno :)

2018-09-10 06:20 UTC, walter-erquinigo commented on app.js
> +    // Photo: { screen: ControlPhotoScreen },
no es bueno poner este tipo de comentarios porque no se sabe si te olvidaste de descomentarlo o si realmente no sirve. puedes ponerle un comentario encima explicando por que' esto es un comentario, si es que es bueno tenerlo ahi como ejemplo, pero si es algo incompleto, mejor ni lo pongas

2018-09-10 06:20 UTC, walter-erquinigo commented on src/components/accordion-content/index.js
> +// navigation
borra esto

2018-09-13 02:51 UTC, NoSaBo requested changes

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/home-screen/index.js
> +      title: "Bienvenido: " + `${navigation.state.params.user}`,
No uses esa linea de bienvenido como titulo, dejala en la data del screen

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.title}>Sede:</Text>
No coloques esto

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.content}>[ Sede ]</Text>
no coloques los corchetes y mapea un valor en el state que tenga el nombre de la sede, creala hardcodeada por mientras

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.title}>Turno:</Text>
aqui tampoco pongas esto

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.content}>[ Horario ]</Text>
Lo mismo que el de arriba

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlSite-screen/index.js
> +    title: 'Control de Sede y Turno',
Ponle "Inicio de Turno" o algo asi...

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlPhoto-screen/index.js
> +          <Text style={styles.content}>[ Empleado ]</Text>
Crea un state hardcodeado del nombre del empleado para que lo mapees aqui.
Quita los corchetes

2018-09-13 02:51 UTC, NoSaBo commented on src/screens/controlPhoto-screen/index.js
> +    title: "Control de foto"
ponle "Autenticacion" o algo asi...

2018-09-13 02:51 UTC, NoSaBo commented on app.js
> +import ControlSiteScreen from "./src/screens/controlSite-screen/index";
Mejor coloca las dos vistas en una misma carpeta, son dos screens pero deben ser similares asi que puedes utilizar el mismo style sheet para las dos cosa que los tamanhos de las letras y cosas sean iguales

2018-09-13 04:42 UTC, renzo-c commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.title}>Sede:</Text>
Te refieres a que en este ya screen no aparezca nada relacionado a la sede?

2018-09-13 04:57 UTC, renzo-c commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.title}>Turno:</Text>
Ya entendí, es la continuación del otro.

2018-09-13 04:59 UTC, NoSaBo commented on src/screens/controlSite-screen/index.js
> +          <Text style={styles.title}>Sede:</Text>
No es necesario que diga Sede: como un label, basta q salga el nombre de la sede y se entenderia :)

2018-09-13 05:04 UTC, renzo-c commented on app.js
> +import ControlSiteScreen from "./src/screens/controlSite-screen/index";
Te refieres a que ControlSiteScreen y ControlPhotoScreen estén en una misma carpeta junto a un solo archivo style.js?

Considerar que este cambio alteraria la regla sobre los nombres index.js

2018-09-13 23:38 UTC, NoSaBo approved these changes

2018-09-13 23:39 UTC, merged