Merge with apollo
NoSaBo/vpProject pull request #9
Opened 2018-09-18 10:09 UTC by NoSaBo

App integrated with apollo and graphql server on heroku.

Login not working yet, login is checking just usernames. 
Active usernames for testing: jreyp, dbuendia

2018-09-18 16:54 UTC, walter-erquinigo requested changes

2018-09-18 16:54 UTC, a20012251 commented on app.js
> +  // uri: "http://localhost:4000/graphql"
si te sirve en el futuro, podrias usar un environment variable para decidir el host, cosa que haces mas faciles tus tests.

2018-09-18 16:54 UTC, a20012251 commented on src/components/accordion-list/index.js
> +        <Text style={styles.header}>Tus Turnos</Text>
lindo

2018-09-18 16:54 UTC, a20012251 commented on src/screens/controlSite-screen/authentication.js
> +      empleado: "Employee.name"
por que esto es un string a secas?

2018-09-18 16:54 UTC, a20012251 commented on src/screens/login-screen/index.js
> +// const FEED_QUERY = gql`
por que no borras esto?

2018-09-18 16:54 UTC, a20012251 commented on src/screens/login-screen/index.js
> +    // this.props.client
borra esta webada, si quieres tenerlo en algun lado por si acaso, create un github gist y ahi lo pones

2018-09-21 07:19 UTC, NoSaBo commented on app.js
> +  // uri: "http://localhost:4000/graphql"
sipirilin, lo agregare luego xD

2018-09-21 07:20 UTC, NoSaBo commented on src/components/accordion-list/index.js
> +        <Text style={styles.header}>Tus Turnos</Text>
xD

2018-09-21 07:21 UTC, NoSaBo commented on src/screens/controlSite-screen/authentication.js
> +      empleado: "Employee.name"
me di cuenta q debo jalarlo del redux no hacer peticiones a cada rato a la bd, asi q lo deje asignado asi porq el cliente iba a verlo y debia saber q ahi iria un nombre :)

2018-09-21 07:21 UTC, NoSaBo commented on src/screens/login-screen/index.js
> +// const FEED_QUERY = gql`
porq aun no esta implementado bien el query/mutation de login en el graphql server y lo voy a necesitar en ese componente :)

2018-09-21 07:28 UTC, NoSaBo commented
xsiaca agregue a este branch la funcionalidad del GPS, revisarlo de nuevo.

2018-10-11 06:46 UTC, merged